/**
 * Created by wallinsondeivesbatistalima on 23/07/17.
 */
export default {
    FETCH_LIST_REQUEST: 'PUBLISHER_FETCH_LIST_REQUEST',
    FETCH_LIST_SUCCESS: 'PUBLISHER_FETCH_LIST_SUCCESS',
    FETCH_LIST_FAILURE: 'PUBLISHER_FETCH_LIST_FAILURE',
    EDITING_ITEM_CHANGE: 'PUBLISHER_EDITING_ITEM_CHANGE',
    EDITING_ITEM_CANCEL: 'PUBLISHER_EDITING_ITEM_CANCEL',
    EDITING_ITEM_SAVE_REQUEST: 'PUBLISHER_EDITING_ITEM_SAVE_REQUEST',
    EDITING_ITEM_SAVE_SUCCESS: 'PUBLISHER_EDITING_ITEM_SAVE_SUCCESS',
    EDITING_ITEM_SAVE_FAILURE: 'PUBLISHER_EDITING_ITEM_SAVE_FAILURE',
    EDITING_ITEM_DELETE_REQUEST: 'PUBLISHER_EDITING_ITEM_DELETE_REQUEST',
    EDITING_ITEM_DELETE_SUCCESS: 'PUBLISHER_EDITING_ITEM_DELETE_SUCCESS',
    EDITING_ITEM_DELETE_FAILURE: 'PUBLISHER_EDITING_ITEM_DELETE_FAILURE',
    CURRENT_ITEM_SELECT: 'PUBLISHER_CURRENT_ITEM_SELECT',
    LOAD_ITEM_PUBLICATIONS_FAILURE : 'PUBLISHER_LOAD_ITEM_PUBLICATIONS_FAILURE',
    LOAD_ITEM_PUBLICATIONS_SUCCESS : 'PUBLISHER_LOAD_ITEM_PUBLICATIONS_SUCCESS',
    LOAD_ITEM_PUBLICATIONS_REQUEST : 'PUBLISHER_LOAD_ITEM_PUBLICATIONS_REQUEST',

};
