/**
 * Created by wallinsondeivesbatistalima on 23/07/17.
 */
export default {
    FETCH_LIST_REQUEST: 'PUBLICATION_FETCH_LIST_REQUEST',
    FETCH_LIST_SUCCESS: 'PUBLICATION_FETCH_LIST_SUCCESS',
    FETCH_LIST_FAILURE: 'PUBLICATION_FETCH_LIST_FAILURE',
    FETCH_PUBLISHER_LIST_REQUEST: 'PUBLISHER_FETCH_LIST_REQUEST',
    FETCH_PUBLISHER_LIST_SUCCESS: 'PUBLISHER_FETCH_LIST_SUCCESS',
    FETCH_PUBLISHER_LIST_FAILURE: 'PUBLISHER_FETCH_LIST_FAILURE',
    FETCH_AUTHOR_LIST_REQUEST: 'AUTHOR_FETCH_LIST_REQUEST',
    FETCH_AUTHOR_LIST_SUCCESS: 'AUTHOR_FETCH_LIST_SUCCESS',
    FETCH_AUTHOR_LIST_FAILURE: 'AUTHOR_FETCH_LIST_FAILURE',
    EDITING_ITEM_CHANGE: 'PUBLICATION_EDITING_ITEM_CHANGE',
    EDITING_ITEM_CANCEL: 'PUBLICATION_EDITING_ITEM_CANCEL',
    EDITING_ITEM_SAVE_REQUEST: 'PUBLICATION_EDITING_ITEM_SAVE_REQUEST',
    EDITING_ITEM_SAVE_SUCCESS: 'PUBLICATION_EDITING_ITEM_SAVE_SUCCESS',
    EDITING_ITEM_SAVE_FAILURE: 'PUBLICATION_EDITING_ITEM_SAVE_FAILURE',
    EDITING_ITEM_DELETE_REQUEST: 'PUBLICATION_EDITING_ITEM_DELETE_REQUEST',
    EDITING_ITEM_DELETE_SUCCESS: 'PUBLICATION_EDITING_ITEM_DELETE_SUCCESS',
    EDITING_ITEM_DELETE_FAILURE: 'PUBLICATION_EDITING_ITEM_DELETE_FAILURE',
    CURRENT_ITEM_SELECT: 'PUBLICATION_CURRENT_ITEM_SELECT',
    BEFORE_START_EDITING1_REQUEST: 'PUBLICATION_BEFORE_START_EDITING_REQUEST',
    BEFORE_START_EDITING1_SUCCESS: 'PUBLICATION_BEFORE_START_EDITING_SUCCESS',
    BEFORE_START_EDITING1_FAILURE: 'PUBLICATION_BEFORE_START_EDITING_FAILURE',
    BEFORE_START_EDITING2_REQUEST: 'PUBLICATION_BEFORE_START_EDITING_REQUEST',
    BEFORE_START_EDITING2_SUCCESS: 'PUBLICATION_BEFORE_START_EDITING_SUCCESS',
    BEFORE_START_EDITING2_FAILURE: 'PUBLICATION_BEFORE_START_EDITING_FAILURE',

};
